services:
  node-red:
    build: ./nodered
    container_name: nodered
    restart: unless-stopped
    networks:
      - nodered_network
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
      - ./nodered/nodes:/data/nodes
    environment:
      - TZ=UTC

  mosquitto:
    build: ./mqtt
    container_name: mosquitto
    restart: unless-stopped
    networks:
      - nodered_network
    ports:
      - "1883:1883"     # Expose MQTT port
      - "9001:9001"     # Expose WebSocket port
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

  php-apache:
    build:
      context: ./apache-root
    container_name: php-apache-server
    ports:
      - "8080:80"
    volumes:
      - ./apache-root:/var/www/html
    restart: unless-stopped


networks:
  nodered_network:
    driver: bridge